/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package Interfaces_graficas;

import javax.swing.JOptionPane;
import skatelab.Administrativo;
import skatelab.Estudiante;
import skatelab.ControladorPerfiles;
import skatelab.Docente;
import skatelab.Usuario;

/**
 *
 * @author ROGER
 */
public class ModificarPerfil extends javax.swing.JFrame {
    public Usuario usuarioEnviado = new Estudiante();

    /** Creates new form ModificarPerfil */
    public ModificarPerfil() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_Volver = new javax.swing.JButton();
        I_ModPerf = new javax.swing.JLabel();
        lbl_ModificarPerf = new javax.swing.JLabel();
        panel_Datos = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txt_Celular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_Correo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_RespSeg = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_ClaveAdmin = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        listaPreguntas = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txt_Contrasena = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_Nombres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txt_Apellidos = new javax.swing.JTextField();
        txt_Cedula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Ocupacion = new javax.swing.JTextField();
        txt_ProgramaM = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        panel_DiasDisp = new javax.swing.JPanel();
        lbl_DiasDisp = new javax.swing.JLabel();
        ch_Lunes = new javax.swing.JCheckBox();
        ch_Martes = new javax.swing.JCheckBox();
        ch_Miercoles = new javax.swing.JCheckBox();
        ch_Jueves = new javax.swing.JCheckBox();
        ch_Viernes = new javax.swing.JCheckBox();
        ch_Sabado = new javax.swing.JCheckBox();
        ch_Domingo = new javax.swing.JCheckBox();
        ch_Si = new javax.swing.JCheckBox();
        ch_No = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        btn_Modificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces_graficas/Imagenes/volver.png"))); // NOI18N

        btn_Volver.setText("Volver");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });

        I_ModPerf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interfaces_graficas/Imagenes/modifPerfil.JPG"))); // NOI18N

        lbl_ModificarPerf.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lbl_ModificarPerf.setText("Modificar Perfil");

        panel_Datos.setBackground(new java.awt.Color(255, 255, 255));
        panel_Datos.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Nombres:");

        txt_Celular.setText("Ingrese Celular");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Apellidos:");

        txt_Correo.setText("Ingrese Correo");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Celular:");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Correo:");

        txt_RespSeg.setText("Ingrese Respuesta");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Pregunta Seguridad:");

        txt_ClaveAdmin.setText("Ingrese Contraseña 2");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Respuesta Seguridad:");

        listaPreguntas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nombre Mascota?", "color Favorito?", "nombre de la madre?", "libro preferido" }));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("claveAdmin");

        txt_Contrasena.setText("Ingrese Contraseña");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cedula:");

        txt_Nombres.setText("Ingrese Nombres");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Contraseña:");

        txt_Apellidos.setText("Ingrese Apellidos");

        txt_Cedula.setForeground(new java.awt.Color(0, 0, 0));
        txt_Cedula.setText("jLabel2");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ocupacion:");

        txt_Ocupacion.setText("Ingrese Ocupacion");

        txt_ProgramaM.setText("Ingrese Programa Matriculado");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("ProgramaMatriculado:");

        javax.swing.GroupLayout panel_DatosLayout = new javax.swing.GroupLayout(panel_Datos);
        panel_Datos.setLayout(panel_DatosLayout);
        panel_DatosLayout.setHorizontalGroup(
            panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DatosLayout.createSequentialGroup()
                        .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_Contrasena)
                            .addComponent(txt_Nombres)
                            .addComponent(txt_Apellidos)
                            .addComponent(txt_Celular)
                            .addComponent(txt_Correo)
                            .addComponent(listaPreguntas, 0, 160, Short.MAX_VALUE)
                            .addComponent(txt_Cedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_DatosLayout.createSequentialGroup()
                        .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ClaveAdmin)
                            .addComponent(txt_RespSeg)
                            .addComponent(txt_Ocupacion)
                            .addComponent(txt_ProgramaM)))))
        );
        panel_DatosLayout.setVerticalGroup(
            panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DatosLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_Cedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_Contrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_Nombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_Apellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_Celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_Correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(listaPreguntas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_RespSeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ClaveAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_Ocupacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txt_ProgramaM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panel_DiasDisp.setBackground(new java.awt.Color(204, 255, 204));
        panel_DiasDisp.setForeground(new java.awt.Color(0, 0, 0));

        lbl_DiasDisp.setForeground(new java.awt.Color(0, 0, 0));
        lbl_DiasDisp.setText("Dias Disponibles: (solo para Docentes)");

        ch_Lunes.setForeground(new java.awt.Color(0, 0, 0));
        ch_Lunes.setText("Lunes");

        ch_Martes.setForeground(new java.awt.Color(0, 0, 0));
        ch_Martes.setText("Martes");

        ch_Miercoles.setForeground(new java.awt.Color(0, 0, 0));
        ch_Miercoles.setText("Miercoles");

        ch_Jueves.setForeground(new java.awt.Color(0, 0, 0));
        ch_Jueves.setText("Jueves");

        ch_Viernes.setForeground(new java.awt.Color(0, 0, 0));
        ch_Viernes.setText("Viernes");

        ch_Sabado.setForeground(new java.awt.Color(0, 0, 0));
        ch_Sabado.setText("Sabado");

        ch_Domingo.setForeground(new java.awt.Color(0, 0, 0));
        ch_Domingo.setText("Domingo");

        ch_Si.setForeground(new java.awt.Color(0, 0, 0));
        ch_Si.setText("Si");

        ch_No.setForeground(new java.awt.Color(0, 0, 0));
        ch_No.setText("No");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Vinculado:");

        javax.swing.GroupLayout panel_DiasDispLayout = new javax.swing.GroupLayout(panel_DiasDisp);
        panel_DiasDisp.setLayout(panel_DiasDispLayout);
        panel_DiasDispLayout.setHorizontalGroup(
            panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DiasDispLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DiasDispLayout.createSequentialGroup()
                        .addGroup(panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ch_Jueves)
                            .addComponent(ch_Viernes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(panel_DiasDispLayout.createSequentialGroup()
                                .addComponent(ch_Si)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ch_No))))
                    .addGroup(panel_DiasDispLayout.createSequentialGroup()
                        .addGroup(panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DiasDisp)
                            .addComponent(ch_Lunes)
                            .addComponent(ch_Martes)
                            .addComponent(ch_Miercoles)
                            .addComponent(ch_Sabado)
                            .addComponent(ch_Domingo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_DiasDispLayout.setVerticalGroup(
            panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_DiasDispLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_DiasDisp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ch_Lunes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch_Martes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch_Miercoles)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_DiasDispLayout.createSequentialGroup()
                        .addComponent(ch_Jueves)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ch_Viernes))
                    .addGroup(panel_DiasDispLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_DiasDispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ch_Si)
                            .addComponent(ch_No))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch_Sabado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ch_Domingo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Modificar.setText("Modificar");
        btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(panel_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addComponent(panel_DiasDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(120, 120, 120))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn_Modificar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Volver)
                .addGap(67, 67, 67)
                .addComponent(I_ModPerf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_ModificarPerf)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btn_Volver))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(I_ModPerf)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lbl_ModificarPerf)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panel_Datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(panel_DiasDisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Modificar)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        // TODO add your handling code here:
        // cerramos la ventana actual
        this.dispose();
        // creamos una instancia de la ventana anterior
        Perfiles ventanaPerfiles = new Perfiles();
        ventanaPerfiles.setVisible(true);
    }//GEN-LAST:event_btn_VolverActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        if (usuarioEnviado.getCarnet()== null) {
            txt_Cedula.setText(String.valueOf(ControladorPerfiles.getSesionActualUsuario().getCarnet()));
            txt_Contrasena.setText(ControladorPerfiles.getSesionActualUsuario().getContrasena());
            txt_Nombres.setText(ControladorPerfiles.getSesionActualUsuario().getNombres());
            txt_Apellidos.setText(ControladorPerfiles.getSesionActualUsuario().getApellidos());
            txt_Celular.setText(String.valueOf(ControladorPerfiles.getSesionActualUsuario().getCelular()));
            txt_Correo.setText(ControladorPerfiles.getSesionActualUsuario().getCorreo());
            txt_RespSeg.setText(ControladorPerfiles.getSesionActualUsuario().getRespuestaSeguridad());

            if (ControladorPerfiles.getSesionActualUsuario() instanceof Estudiante) {            
                txt_ProgramaM.setText(((Estudiante)ControladorPerfiles.getSesionActualUsuario()).getProgramaMatriculado());
                txt_ClaveAdmin.setText("Solo Administradores");
            }else if (ControladorPerfiles.getSesionActualUsuario() instanceof Docente) {
                
                Boolean vinculado = ((Docente)ControladorPerfiles.getSesionActualUsuario()).getVinculado();
                if (vinculado) {
                    ch_Si.setSelected(true);
                }else{
                    ch_No.setSelected(true);
                }
                txt_ClaveAdmin.setText("Solo Administradores");

                String diasDisp = ((Docente)ControladorPerfiles.getSesionActualUsuario()).getCodigoDias();
                for (int i = 0; i < diasDisp.length(); i++) {
                    switch (diasDisp.charAt(i)) {
                        case '1':
                            ch_Lunes.setSelected(true);
                            break;
                        case '2':
                            ch_Martes.setSelected(true);                        
                            break;
                        case '3':
                            ch_Miercoles.setSelected(true);                        
                            break;
                        case '4':
                            ch_Jueves.setSelected(true);
                            break;
                        case '5':
                            ch_Viernes.setSelected(true);
                            break;
                        case '6':
                            ch_Sabado.setSelected(true);
                            break;
                        case '7':
                            ch_Domingo.setSelected(true);
                            break;
                        default:
                            throw new AssertionError();
                    }

                }

            }else if (ControladorPerfiles.getSesionActualUsuario() instanceof Docente){
                txt_Ocupacion.setText(txt_ClaveAdmin.getText());
                txt_ClaveAdmin.setText(((Administrativo)ControladorPerfiles.getSesionActualUsuario()).getClaveAdmin());                    
            }
            
        }else{
            txt_Cedula.setText(String.valueOf(usuarioEnviado.getCedula()));
            txt_Contrasena.setText(String.valueOf(usuarioEnviado.getContrasena()));
            txt_Nombres.setText(usuarioEnviado.getNombres());
            txt_Apellidos.setText(usuarioEnviado.getApellidos());
            txt_Celular.setText(String.valueOf(usuarioEnviado.getCelular()));
            txt_Correo.setText(usuarioEnviado.getCorreo());
            txt_RespSeg.setText(usuarioEnviado.getRespuestaSeguridad());

            if (usuarioEnviado instanceof Estudiante) {            
                txt_Ocupacion.setText(((Estudiante)usuarioEnviado).txt_ClaveAdmin;
                txt_Contrasena2.setText("Solo Administradores");
            }else if (usuarioEnviado instanceof Docente) {
                txt_Ocupacion.setText(txt_ClaveAdmin;
                txt_Contrasena2.setText("Solo Administradores");

                String diasDisp = ((Docente)usuarioEnviado).getDiasDisp();
                for (int i = 0; i < diasDisp.length(); i++) {
                    switch (diasDisp.charAt(i)) {
                        case '1':
                            ch_Lunes.setSelected(true);
                            break;
                        case '2':
                            ch_Martes.setSelected(true);                        
                            break;
                        case '3':
                            ch_Miercoles.setSelected(true);                        
                            break;
                        case '4':
                            ch_Jueves.setSelected(true);
                            break;
                        case '5':
                            ch_Viernes.setSelected(true);
                            break;
                        case '6':
                            ch_Sabado.setSelected(true);
                            break;
                        case '7':
                            ch_Domingo.setSelected(true);
                            break;
                        default:
                            throw new AssertionError();
                    }

                }

            }else{
                txt_Ocupacion.setText(txt_ClaveAdmin;
                txt_Contrasena2.setText(((Administrativo)usuarioEnviado).getContrasena2());                    
            }
        
        }
        
    }//GEN-LAST:event_formWindowOpened

    private void btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarActionPerformed
        // TODO add your handling code here:
        if (usuarioEnviado.getCedula() == null){
            try {
            if (ControladorPerfiles.getSesionActualUsuario() instanceof Estudiante) {
            ControladorPerfiles.getSesionActualUsuario().setContrasena(Integer.parseInt(txt_Contrasena.getText()));
            ControladorPerfiles.getSesionActualUsuario().setRespuestaSeguridad(txt_RespSeg.getText());
            ControladorPerfiles.getSesionActualUsuario().setNombres(txt_Nombres.getText());
            ControladorPerfiles.getSesionActualUsuario().setApellidos(txt_Apellidos.getText());
            ControladorPerfiles.getSesionActualUsuario().setCelular(Long.parseLong(txt_Celular.getText()));
            ControladorPerfiles.getSesionActualUsuario().setCorreo(txt_Correo.getText());
            ((Estudiante)ControladorPerfiles.getSesionActualUsuario()).setOcupacion(txt_Ocupacion.getText());
            
            
            
            ControladorPerfiles.actualizarPerfil(ControladorPerfiles.getSesionActualUsuario());
            
        }else if (ControladorPerfiles.getSesionActualUsuario() instanceof Docente) {
            ControladorPerfiles.getSesionActualUsuario().setContrasena(Integer.parseInt(txt_Contrasena.getText()));
            ControladorPerfiles.getSesionActualUsuario().setRespuestaSeguridad(txt_RespSeg.getText());
            ControladorPerfiles.getSesionActualUsuario().setNombres(txt_Nombres.getText());
            ControladorPerfiles.getSesionActualUsuario().setApellidos(txt_Apellidos.getText());
            ControladorPerfiles.getSesionActualUsuario().setCelular(Long.parseLong(txt_Celular.getText()));
            ControladorPerfiles.getSesionActualUsuario().setCorreo(txt_Correo.getText());
            
                boolean estadoLunes = ch_Lunes.isSelected();
                boolean estadoMartes = ch_Martes.isSelected();
                boolean estadoMiercoles = ch_Miercoles.isSelected();
                boolean estadoJueves = ch_Jueves.isSelected();
                boolean estadoViernes = ch_Viernes.isSelected();
                boolean estadoSabado = ch_Sabado.isSelected();
                boolean estadoDomingo = ch_Domingo.isSelected();
                String diasDisp = "";
                
                boolean[] codigoDiasDisp = new boolean[7];
                codigoDiasDisp[0]=estadoLunes;
                codigoDiasDisp[1]=estadoMartes;
                codigoDiasDisp[2]=estadoMiercoles;
                codigoDiasDisp[3]=estadoJueves;
                codigoDiasDisp[4]=estadoViernes;
                codigoDiasDisp[5]=estadoSabado;
                codigoDiasDisp[6]=estadoDomingo;
                for (int i = 0; i < 7; i++) {
                    if (codigoDiasDisp[i]== true) {
                        diasDisp = diasDisp + (i+1);
                    }
                    
                }
            
            ((Docente)ControladorPerfiles.getSesionActualUsuario()).setDiasDisp(diasDisp);
            
            
            
            ControladorPerfiles.actualizarPerfil(ControladorPerfiles.getSesionActualUsuario());
            
            
        }else{
            ControladorPerfiles.getSesionActualUsuario().setContrasena(Integer.parseInt(txt_Contrasena.getText()));
            ControladorPerfiles.getSesionActualUsuario().setRespuestaSeguridad(txt_RespSeg.getText());
            ControladorPerfiles.getSesionActualUsuario().setNombres(txt_Nombres.getText());
            ControladorPerfiles.getSesionActualUsuario().setApellidos(txt_Apellidos.getText());
            ControladorPerfiles.getSesionActualUsuario().setCelular(Long.parseLong(txt_Celular.getText()));
            ControladorPerfiles.getSesionActualUsuario().setCorreo(txt_Correo.getText());
            ((Administrativo)ControladorPerfiles.getSesiotxt_ClaveAdmin)).setContrasena2(txt_Contrasena2.getText());
            
            ControladorPerfiles.actualizarPerfil(ControladorPerfiles.getSesionActualUsuario());
        
        }
            JOptionPane.showMessageDialog(null, "Perfil Actualizado con exito");
            
            this.dispose();
            Perfiles ventanaPerfiles = new Perfiles();
            ventanaPerfiles.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debes Ingresar Por lo Menos Un Dato Correcto, Verifica los datos ingresados sean Validos");
        }
        
        }else{
            try {
            if (usuarioEnviado instanceof Estudiante) {
            usuarioEnviado.setContrasena(Integer.parseInt(txt_Contrasena.getText()));
            usuarioEnviado.setRespuestaSeguridad(txt_RespSeg.getText());
            usuarioEnviado.setNombres(txt_Nombres.getText());
            usuarioEnviado.setApellidos(txt_Apellidos.getText());
            usuarioEnviado.setCelular(Long.parseLong(txt_Celular.getText()));
            usuarioEnviado.setCorreo(txt_Correo.getText());
            ((Estudiante)usuarioEnviado).setOcupacion(txt_Ocupacion.getText());
            
            
            
            ControladorPerfiles.actualizarPerfil(usuarioEnviado);
            
        }else if (usuarioEnviado instanceof Docente) {
            usuarioEnviado.setContrasena(Integer.parseInt(txt_Contrasena.getText()));
            usuarioEnviado.setRespuestaSeguridad(txt_RespSeg.getText());
            usuarioEnviado.setNombres(txt_Nombres.getText());
            usuarioEnviado.setApellidos(txt_Apellidos.getText());
            usuarioEnviado.setCelular(Long.parseLong(txt_Celular.getText()));
            usuarioEnviado.setCorreo(txt_Correo.getText());
            
                boolean estadoLunes = ch_Lunes.isSelected();
                boolean estadoMartes = ch_Martes.isSelected();
                boolean estadoMiercoles = ch_Miercoles.isSelected();
                boolean estadoJueves = ch_Jueves.isSelected();
                boolean estadoViernes = ch_Viernes.isSelected();
                boolean estadoSabado = ch_Sabado.isSelected();
                boolean estadoDomingo = ch_Domingo.isSelected();
                String diasDisp = "";
                
                boolean[] codigoDiasDisp = new boolean[7];
                codigoDiasDisp[0]=estadoLunes;
                codigoDiasDisp[1]=estadoMartes;
                codigoDiasDisp[2]=estadoMiercoles;
                codigoDiasDisp[3]=estadoJueves;
                codigoDiasDisp[4]=estadoViernes;
                codigoDiasDisp[5]=estadoSabado;
                codigoDiasDisp[6]=estadoDomingo;
                for (int i = 0; i < 7; i++) {
                    if (codigoDiasDisp[i]== true) {
                        diasDisp = diasDisp + (i+1);
                    }
                    
                }
            
            ((Docente)usuarioEnviado).setDiasDisp(diasDisp);
            
            
            
            ControladorPerfiles.actualizarPerfil(usuarioEnviado);
            
            
        }else{
            usuarioEnviado.setContrasena(Integer.parseInt(txt_Contrasena.getText()));
            usuarioEnviado.setRespuestaSeguridad(txt_RespSeg.getText());
            usuarioEnviado.setNombres(txt_Nombres.getText());
            usuarioEnviado.setApellidos(txt_Apellidos.getText());
            usuarioEnviado.setCelular(Long.parseLong(txt_Celular.getText()));
            usuarioEnviado.setCorreo(txt_Correo.getText());
            ((Administrativtxt_ClaveAdmino).setContrasena2(txt_Contrasena2.getText());
            
            ControladorPerfiles.actualizarPerfil(usuarioEnviado);
        
        }
            JOptionPane.showMessageDialog(null, "Perfil Actualizado con exito");
            
            this.dispose();
            Perfiles ventanaPerfiles = new Perfiles();
            ventanaPerfiles.setVisible(true);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Debes Ingresar Por lo Menos Un Dato Correcto, Verifica los datos ingresados sean Validos");
        }
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btn_ModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPerfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel I_ModPerf;
    private javax.swing.JButton btn_Modificar;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JCheckBox ch_Domingo;
    private javax.swing.JCheckBox ch_Jueves;
    private javax.swing.JCheckBox ch_Lunes;
    private javax.swing.JCheckBox ch_Martes;
    private javax.swing.JCheckBox ch_Miercoles;
    private javax.swing.JCheckBox ch_No;
    private javax.swing.JCheckBox ch_Sabado;
    private javax.swing.JCheckBox ch_Si;
    private javax.swing.JCheckBox ch_Viernes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lbl_DiasDisp;
    private javax.swing.JLabel lbl_ModificarPerf;
    private javax.swing.JComboBox<String> listaPreguntas;
    private javax.swing.JPanel panel_Datos;
    private javax.swing.JPanel panel_DiasDisp;
    private javax.swing.JTextField txt_Apellidos;
    private javax.swing.JLabel txt_Cedula;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_ClaveAdmin;
    private javax.swing.JTextField txt_Contrasena;
    private javax.swing.JTextField txt_Correo;
    private javax.swing.JTextField txt_Nombres;
    private javax.swing.JTextField txt_Ocupacion;
    private javax.swing.JTextField txt_ProgramaM;
    private javax.swing.JTextField txt_RespSeg;
    // End of variables declaration//GEN-END:variables

    public Usuario getUsuarioEnviado() {
        return usuarioEnviado;
    }

    public void setUsuarioEnviado(Usuario usuarioEnviado) {
        this.usuarioEnviado = usuarioEnviado;
    }

}
